esphome:
  name: "wmbusmaster-esp32"
  friendly_name: WMbus ESP32

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  networks:
    - ssid: !secret wifi_ssid
    - password: !secret wifi_password
    - ssid: !secret 1_wifi_ssid
    - password: !secret 1_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "WMbus Hotspot pass: itheuca012"
    password: "itheuca012"

switch:
  - platform: factory_reset
    name: Restart with Factory Default Settings

button:
  - platform: restart
    name: "WMbus Restart"

captive_portal:
web_server:
  port: 80

external_components:
  - source: github://SzczepanLeon/esphome-components@version_4 # ESP32, Arduino, CC1101
    components: [ wmbus ]

time:
  - platform: sntp
    id: time_sntp

wmbus:
  sync_mode: True
  log_all: True
  
  mosi_pin: GPIO23 ## SI   
  miso_pin: GPIO19 ## SO   
  clk_pin:  GPIO18 ## SCLK 
  cs_pin:   GPIO21 ## CSN  
  gdo0_pin: GPIO25 ## GD00 
  gdo2_pin: GPIO26 ## GD02 






